web:
  - command: gunicorn -w 4 -b 0.0.0.0:$PORT solar.wsgi:application
    healthCheck:
      path: /healthcheck
      intervalSeconds: 10
      timeoutSeconds: 5
    instanceCount: 1
    name: gunicorn
